Fail the workflow if the regression tests fail

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -48,23 +48,37 @@ jobs:
       - name: test  # TODO make this part run in parallel
         run: |
           ./run.sh rmg/aromatics no
-          echo "aromatics status: ${?}"
+          aromatics_status=$?
+          echo "aromatics status: $aromatics_status=$?"
           ./run.sh rmg/nitrogen no
-          echo "nitrogen status: ${?}"
+          nitrogen_status=$?
+          echo "nitrogen status: $nitrogen_status"
           ./run.sh rmg/sulfur no
-          echo "sulfur status: ${?}"
+          sulfur_status=$?
+          echo "sulfur status: $sulfur_status"
           ./run.sh rmg/oxidation no
-          echo "oxidation status: ${?}"
+          oxidation_status=$?
+          echo "oxidation status: $oxidation_status"
           ./run.sh rmg/liquid_oxidation no
-          echo "liquid oxidation status: ${?}"
+          liquid_oxidation_status=$?
+          echo "liquid oxidation status: $liquid_oxidation_status"
           ./run.sh rmg/superminimal no
-          echo "superminimal status: ${?}"
+          superminimal_status=$?
+          echo "superminimal status: $superminimal_status"
           ./run.sh examples/eg1 no
-          echo "eg1 status: ${?}"
+          eg1_status=$?
+          echo "eg1 status: $eg1_status"
+          if [ $(($aromatics_status | $nitrogen_status | $sulfur_status | $oxidation_status | $liquid_oxidation_status | $superminimal_status | eg1_status)) -ne 0 ];
+          then
+            echo "Failed regression tests"
+            exit 1
+          fi
       - name: finish  # TODO check that this works as expected for both success and failure
+        if: always()
         run: |
           if [ ${{ job.status }} == 'success' ]; then
             ./after_success.sh
           else
             ./after_failure.sh
           fi
+          
